### ISSUE TITLE
Get a reference to a formly field component in lifecycle hook

### ISSUE THREAD

**Issue by Etchelon** [formly-js/ngx-formly#1160]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[X] feature request
[X] support request
```

**Current behavior**
I am not able to get a reference to an instance of a formly field custom component in the lifecycle hook.

**Expected behavior**
I have created a custom component which extends FieldType, and I defined an Output property. I want to be able to subscribe to that EventEmitter in the lifecycle hook that I defined (an afterViewInit function) in order to react to those events. Currently, the lifecycle hooks callback are provided only with the FormlyFieldConfig object and not a way to retrieve the component instance.
Here:
![image](https://user-images.githubusercontent.com/4141889/44981763-dede2380-af73-11e8-9686-d40a1a65af40.png)
I'd like the function to also receive `this.componentRefs[index].instance`, where index is the index of the component instance referring to this.field.

**What is the motivation / use case for changing the behavior?**
To be able to achieve higher control over multiple events that can be defined in custom controls.

* **Angular version:** 6.0.X

**Comment by aitboudad** [comment]
during initialization assign the output to field templateOptions instead.

**Comment by Etchelon** [comment]
Sorry, can you expand on that? The output of what?

**Comment by Etchelon** [comment]
https://stackblitz.com/edit/angular-5tmmzk?file=src/app/app.component.ts

**Comment by aitboudad** [comment]
https://stackblitz.com/edit/angular-5tmmzk-gzvoca

**Comment by Etchelon** [comment]
The example I posted is an over simplification that wanted to explain my need.
What I'm actually doing is writing a library that wraps formly and allows any user to create a dynamic form visually, through a UI that generates a simple json (no javascript). This json is then interpreted and translated by the library to a set of FormlyFieldConfig objects.
Among the things you can do is specify automated actions: for example, when field A emits an event, act accordingly on field B. I implemented these actions in the afterViewInit lifecycle hook but in order to respond to certain custom events, specified in my custom field types, I need to subscribe to the EventEmitters on the instances of those field types. And since the FieldType class has a reference to such instance, I'd like to have it passed inside the lifecycle hook in some way.

**Comment by aitboudad** [comment]
still not clear to me anyway in v5 we have introduced an extension feature that allow to hook over the field see the following issue for more details https://github.com/formly-js/ngx-formly/issues/1109#issuecomment-412137737
