### ISSUE TITLE
Input type number 

### ISSUE THREAD

**Issue by Pat-Lovelace** [formly-js/ngx-formly#729]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[x ] feature request
[ ] support request
```

**Current behavior**
I have a field which type is an "input" but in their templateOptions is determinated as "number:

``` javascript
formFields: Array<FormlyFieldConfig> = [
    {
      className: 'col-xs-12',
      type: 'input',
      key: 'input1',
      templateOptions: {
        type: 'number',
        label: 'model-number',
        min: 0
      }
    }
  ];
```

The model associated to this field is a string type. 
```json
{"input1":"123"} 
```

Furthermore, if I specify "min": 0, and I insert a negative number, the error exception associated to "min" is not thrown.  But if I specify "min": 1, and I put a negative number, the error exception is, indeed, thrown. 

**Expected behavior**
I would like to have the model associated to this field as a number type. 
```json
{"input1":123} 
```

And I would like the error exception associated to "min" thrown when "min":0 and the model is a negative number. 

**Minimal reproduction of the problem with instructions**
[Example](https://stackblitz.com/edit/angular-pui9yb)

**What is the motivation / use case for changing the behavior?**
I think that the type linked to an input number type should be a number, and the negative values should be managed if min value is 0.

Thank you for your time and consideration!

**Please tell us about your environment:**
[Not relevant]

* **Angular version:** 5.2.5

* **Browser:** [ Chrome 63.0.3239.132]
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by aitboudad** [comment]
fixed and released in `2.0.0-rc.28`.

**Comment by Pat-Lovelace** [comment]
Thanks! I've just checked your release 2.0.0-rc.29 and the solution about the number type works great! 

But the problem with min: 0 persists... if I insert a negative number, the min error is not thrown...

**Comment by Pat-Lovelace** [comment]
Thanks a lot! Now it works perfect ;)

**Comment by pietromarrone** [comment]
It seems that Material is still not working, The model associated to this field is a string type.

**Comment by aitboudad** [comment]
@pietromarrone can you fill a new issue, thanks!

**Comment by dimosthenis-k** [comment]
Hello, it seems like this issue persists in PrimeNG. Generating a field through JSON Schema with "type":"number" renders an input field that emmits a string value.

**Comment by aitboudad** [comment]
@dimosthenis-k please create a new issue with a reproduction example.
